//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AracTakipDb : DbContext
    {
        public AracTakipDb()
            : base("name=AracTakipDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ACCESSORY> TBL_ACCESSORY { get; set; }
        public virtual DbSet<TBL_ALARM> TBL_ALARM { get; set; }
        public virtual DbSet<TBL_ALARM_DETAILS> TBL_ALARM_DETAILS { get; set; }
        public virtual DbSet<TBL_ARCHIVE> TBL_ARCHIVE { get; set; }
        public virtual DbSet<TBL_CALISMA> TBL_CALISMA { get; set; }
        public virtual DbSet<TBL_COMPANY> TBL_COMPANY { get; set; }
        public virtual DbSet<TBL_DATA_MESSAGES> TBL_DATA_MESSAGES { get; set; }
        public virtual DbSet<TBL_DURAK_DETAY> TBL_DURAK_DETAY { get; set; }
        public virtual DbSet<TBL_DURAK_GIRIS_CIKIS> TBL_DURAK_GIRIS_CIKIS { get; set; }
        public virtual DbSet<TBL_DURAK_IHLAL_MASTER> TBL_DURAK_IHLAL_MASTER { get; set; }
        public virtual DbSet<TBL_DURAK_TANIM> TBL_DURAK_TANIM { get; set; }
        public virtual DbSet<TBL_DURAKLAR_ARASI_SURE_TANIM> TBL_DURAKLAR_ARASI_SURE_TANIM { get; set; }
        public virtual DbSet<TBL_DURAKLAR_ARASI_SURELER> TBL_DURAKLAR_ARASI_SURELER { get; set; }
        public virtual DbSet<TBL_DURMA> TBL_DURMA { get; set; }
        public virtual DbSet<TBL_INDEKS_DETAILS> TBL_INDEKS_DETAILS { get; set; }
        public virtual DbSet<TBL_INVOICE> TBL_INVOICE { get; set; }
        public virtual DbSet<TBL_KOMUT> TBL_KOMUT { get; set; }
        public virtual DbSet<TBL_MSG_TYPE> TBL_MSG_TYPE { get; set; }
        public virtual DbSet<TBL_PERSONNEL> TBL_PERSONNEL { get; set; }
        public virtual DbSet<TBL_PROG_ANSWER> TBL_PROG_ANSWER { get; set; }
        public virtual DbSet<TBL_READ_IDENTITY> TBL_READ_IDENTITY { get; set; }
        public virtual DbSet<TBL_RFIDCARD> TBL_RFIDCARD { get; set; }
        public virtual DbSet<TBL_SEFER_PAKETI> TBL_SEFER_PAKETI { get; set; }
        public virtual DbSet<TBL_STATUS_DETAILS> TBL_STATUS_DETAILS { get; set; }
        public virtual DbSet<TBL_TERMINAL> TBL_TERMINAL { get; set; }
        public virtual DbSet<TBL_USER> TBL_USER { get; set; }
        public virtual DbSet<test> test { get; set; }
    
        public virtual ObjectResult<SP_AktiviteRaporuByTerminalId_Result> SP_AktiviteRaporuByTerminalId(Nullable<int> terminalId, Nullable<System.DateTime> dateBaslama, Nullable<System.DateTime> dateBitme)
        {
            var terminalIdParameter = terminalId.HasValue ?
                new ObjectParameter("TerminalId", terminalId) :
                new ObjectParameter("TerminalId", typeof(int));
    
            var dateBaslamaParameter = dateBaslama.HasValue ?
                new ObjectParameter("DateBaslama", dateBaslama) :
                new ObjectParameter("DateBaslama", typeof(System.DateTime));
    
            var dateBitmeParameter = dateBitme.HasValue ?
                new ObjectParameter("DateBitme", dateBitme) :
                new ObjectParameter("DateBitme", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AktiviteRaporuByTerminalId_Result>("SP_AktiviteRaporuByTerminalId", terminalIdParameter, dateBaslamaParameter, dateBitmeParameter);
        }
    
        public virtual ObjectResult<SP_AnaKullaniciAraclari_Result> SP_AnaKullaniciAraclari(Nullable<int> upperCompany)
        {
            var upperCompanyParameter = upperCompany.HasValue ?
                new ObjectParameter("UpperCompany", upperCompany) :
                new ObjectParameter("UpperCompany", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AnaKullaniciAraclari_Result>("SP_AnaKullaniciAraclari", upperCompanyParameter);
        }
    
        public virtual ObjectResult<SP_AracBilgileribyCompanyId_Result> SP_AracBilgileribyCompanyId(Nullable<int> companyId, Nullable<System.DateTime> bastarihi, Nullable<System.DateTime> bittarihi)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var bastarihiParameter = bastarihi.HasValue ?
                new ObjectParameter("bastarihi", bastarihi) :
                new ObjectParameter("bastarihi", typeof(System.DateTime));
    
            var bittarihiParameter = bittarihi.HasValue ?
                new ObjectParameter("bittarihi", bittarihi) :
                new ObjectParameter("bittarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AracBilgileribyCompanyId_Result>("SP_AracBilgileribyCompanyId", companyIdParameter, bastarihiParameter, bittarihiParameter);
        }
    
        public virtual ObjectResult<SP_AracBilgileriByTerminalId_Result> SP_AracBilgileriByTerminalId(Nullable<int> terminalID, Nullable<System.DateTime> baslamatarihi, Nullable<System.DateTime> bitmetarihi)
        {
            var terminalIDParameter = terminalID.HasValue ?
                new ObjectParameter("terminalID", terminalID) :
                new ObjectParameter("terminalID", typeof(int));
    
            var baslamatarihiParameter = baslamatarihi.HasValue ?
                new ObjectParameter("baslamatarihi", baslamatarihi) :
                new ObjectParameter("baslamatarihi", typeof(System.DateTime));
    
            var bitmetarihiParameter = bitmetarihi.HasValue ?
                new ObjectParameter("bitmetarihi", bitmetarihi) :
                new ObjectParameter("bitmetarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AracBilgileriByTerminalId_Result>("SP_AracBilgileriByTerminalId", terminalIDParameter, baslamatarihiParameter, bitmetarihiParameter);
        }
    
        public virtual ObjectResult<SP_AracListesi_Result> SP_AracListesi(Nullable<int> companyId, Nullable<System.DateTime> dateBaslama)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var dateBaslamaParameter = dateBaslama.HasValue ?
                new ObjectParameter("DateBaslama", dateBaslama) :
                new ObjectParameter("DateBaslama", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AracListesi_Result>("SP_AracListesi", companyIdParameter, dateBaslamaParameter);
        }
    
        public virtual ObjectResult<SP_AracListesiByUpperCompanyId_Result> SP_AracListesiByUpperCompanyId(Nullable<int> companyId, Nullable<System.DateTime> dateBaslama)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var dateBaslamaParameter = dateBaslama.HasValue ?
                new ObjectParameter("DateBaslama", dateBaslama) :
                new ObjectParameter("DateBaslama", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AracListesiByUpperCompanyId_Result>("SP_AracListesiByUpperCompanyId", companyIdParameter, dateBaslamaParameter);
        }
    
        public virtual ObjectResult<SP_CalismaRaporuByTerminalId_Result> SP_CalismaRaporuByTerminalId(Nullable<int> terminalID, Nullable<System.DateTime> baslamatarihi, Nullable<System.DateTime> bitmetarihi)
        {
            var terminalIDParameter = terminalID.HasValue ?
                new ObjectParameter("terminalID", terminalID) :
                new ObjectParameter("terminalID", typeof(int));
    
            var baslamatarihiParameter = baslamatarihi.HasValue ?
                new ObjectParameter("baslamatarihi", baslamatarihi) :
                new ObjectParameter("baslamatarihi", typeof(System.DateTime));
    
            var bitmetarihiParameter = bitmetarihi.HasValue ?
                new ObjectParameter("bitmetarihi", bitmetarihi) :
                new ObjectParameter("bitmetarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CalismaRaporuByTerminalId_Result>("SP_CalismaRaporuByTerminalId", terminalIDParameter, baslamatarihiParameter, bitmetarihiParameter);
        }
    
        public virtual ObjectResult<SP_CalismaSuresiByCompanyId_Result> SP_CalismaSuresiByCompanyId(Nullable<int> companyId, Nullable<System.DateTime> bastarihi, Nullable<System.DateTime> bittarihi)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var bastarihiParameter = bastarihi.HasValue ?
                new ObjectParameter("bastarihi", bastarihi) :
                new ObjectParameter("bastarihi", typeof(System.DateTime));
    
            var bittarihiParameter = bittarihi.HasValue ?
                new ObjectParameter("bittarihi", bittarihi) :
                new ObjectParameter("bittarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CalismaSuresiByCompanyId_Result>("SP_CalismaSuresiByCompanyId", companyIdParameter, bastarihiParameter, bittarihiParameter);
        }
    
        public virtual ObjectResult<SP_CalismaSuresiByTerminalId_Result> SP_CalismaSuresiByTerminalId(Nullable<int> terminalID, Nullable<System.DateTime> baslamatarihi, Nullable<System.DateTime> bitmetarihi)
        {
            var terminalIDParameter = terminalID.HasValue ?
                new ObjectParameter("terminalID", terminalID) :
                new ObjectParameter("terminalID", typeof(int));
    
            var baslamatarihiParameter = baslamatarihi.HasValue ?
                new ObjectParameter("baslamatarihi", baslamatarihi) :
                new ObjectParameter("baslamatarihi", typeof(System.DateTime));
    
            var bitmetarihiParameter = bitmetarihi.HasValue ?
                new ObjectParameter("bitmetarihi", bitmetarihi) :
                new ObjectParameter("bitmetarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CalismaSuresiByTerminalId_Result>("SP_CalismaSuresiByTerminalId", terminalIDParameter, baslamatarihiParameter, bitmetarihiParameter);
        }
    
        public virtual int SP_CalismaSuresiInsert(Nullable<int> terminalId)
        {
            var terminalIdParameter = terminalId.HasValue ?
                new ObjectParameter("TerminalId", terminalId) :
                new ObjectParameter("TerminalId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CalismaSuresiInsert", terminalIdParameter);
        }
    
        public virtual ObjectResult<SP_DetayliMesafeRaporu_Result> SP_DetayliMesafeRaporu(Nullable<int> terminalId, Nullable<System.DateTime> dateBaslama, Nullable<System.DateTime> dateBitme)
        {
            var terminalIdParameter = terminalId.HasValue ?
                new ObjectParameter("TerminalId", terminalId) :
                new ObjectParameter("TerminalId", typeof(int));
    
            var dateBaslamaParameter = dateBaslama.HasValue ?
                new ObjectParameter("DateBaslama", dateBaslama) :
                new ObjectParameter("DateBaslama", typeof(System.DateTime));
    
            var dateBitmeParameter = dateBitme.HasValue ?
                new ObjectParameter("DateBitme", dateBitme) :
                new ObjectParameter("DateBitme", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DetayliMesafeRaporu_Result>("SP_DetayliMesafeRaporu", terminalIdParameter, dateBaslamaParameter, dateBitmeParameter);
        }
    
        public virtual ObjectResult<SP_DurakIhlalleribyCompanyId_Result> SP_DurakIhlalleribyCompanyId(Nullable<int> companyId, Nullable<System.DateTime> baslamatarihi, Nullable<System.DateTime> bitmetarihi)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("companyId", companyId) :
                new ObjectParameter("companyId", typeof(int));
    
            var baslamatarihiParameter = baslamatarihi.HasValue ?
                new ObjectParameter("baslamatarihi", baslamatarihi) :
                new ObjectParameter("baslamatarihi", typeof(System.DateTime));
    
            var bitmetarihiParameter = bitmetarihi.HasValue ?
                new ObjectParameter("bitmetarihi", bitmetarihi) :
                new ObjectParameter("bitmetarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DurakIhlalleribyCompanyId_Result>("SP_DurakIhlalleribyCompanyId", companyIdParameter, baslamatarihiParameter, bitmetarihiParameter);
        }
    
        public virtual ObjectResult<SP_DuraklamaRaporu_Result> SP_DuraklamaRaporu(Nullable<int> companyId, Nullable<System.DateTime> dateBaslama)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var dateBaslamaParameter = dateBaslama.HasValue ?
                new ObjectParameter("DateBaslama", dateBaslama) :
                new ObjectParameter("DateBaslama", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DuraklamaRaporu_Result>("SP_DuraklamaRaporu", companyIdParameter, dateBaslamaParameter);
        }
    
        public virtual ObjectResult<SP_DurmaRaporuByTerminalId_Result> SP_DurmaRaporuByTerminalId(Nullable<int> terminalID, Nullable<System.DateTime> baslamatarihi, Nullable<System.DateTime> bitmetarihi)
        {
            var terminalIDParameter = terminalID.HasValue ?
                new ObjectParameter("terminalID", terminalID) :
                new ObjectParameter("terminalID", typeof(int));
    
            var baslamatarihiParameter = baslamatarihi.HasValue ?
                new ObjectParameter("baslamatarihi", baslamatarihi) :
                new ObjectParameter("baslamatarihi", typeof(System.DateTime));
    
            var bitmetarihiParameter = bitmetarihi.HasValue ?
                new ObjectParameter("bitmetarihi", bitmetarihi) :
                new ObjectParameter("bitmetarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DurmaRaporuByTerminalId_Result>("SP_DurmaRaporuByTerminalId", terminalIDParameter, baslamatarihiParameter, bitmetarihiParameter);
        }
    
        public virtual ObjectResult<SP_DurmaSuresiByCompanyId_Result> SP_DurmaSuresiByCompanyId(Nullable<int> companyId, Nullable<System.DateTime> bastarihi, Nullable<System.DateTime> bittarihi)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var bastarihiParameter = bastarihi.HasValue ?
                new ObjectParameter("bastarihi", bastarihi) :
                new ObjectParameter("bastarihi", typeof(System.DateTime));
    
            var bittarihiParameter = bittarihi.HasValue ?
                new ObjectParameter("bittarihi", bittarihi) :
                new ObjectParameter("bittarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DurmaSuresiByCompanyId_Result>("SP_DurmaSuresiByCompanyId", companyIdParameter, bastarihiParameter, bittarihiParameter);
        }
    
        public virtual ObjectResult<SP_DurmaSuresiByTerminalId_Result> SP_DurmaSuresiByTerminalId(Nullable<int> terminalID, Nullable<System.DateTime> baslamatarihi, Nullable<System.DateTime> bitmetarihi)
        {
            var terminalIDParameter = terminalID.HasValue ?
                new ObjectParameter("terminalID", terminalID) :
                new ObjectParameter("terminalID", typeof(int));
    
            var baslamatarihiParameter = baslamatarihi.HasValue ?
                new ObjectParameter("baslamatarihi", baslamatarihi) :
                new ObjectParameter("baslamatarihi", typeof(System.DateTime));
    
            var bitmetarihiParameter = bitmetarihi.HasValue ?
                new ObjectParameter("bitmetarihi", bitmetarihi) :
                new ObjectParameter("bitmetarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DurmaSuresiByTerminalId_Result>("SP_DurmaSuresiByTerminalId", terminalIDParameter, baslamatarihiParameter, bitmetarihiParameter);
        }
    
        public virtual int SP_DurmaSuresiInsert(Nullable<int> terminalId)
        {
            var terminalIdParameter = terminalId.HasValue ?
                new ObjectParameter("TerminalId", terminalId) :
                new ObjectParameter("TerminalId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DurmaSuresiInsert", terminalIdParameter);
        }
    
        public virtual ObjectResult<SP_Gecmis_Izleme_Result> SP_Gecmis_Izleme(Nullable<int> terminalId, Nullable<System.DateTime> baslamaZamani, Nullable<System.DateTime> bitmeZamani)
        {
            var terminalIdParameter = terminalId.HasValue ?
                new ObjectParameter("TerminalId", terminalId) :
                new ObjectParameter("TerminalId", typeof(int));
    
            var baslamaZamaniParameter = baslamaZamani.HasValue ?
                new ObjectParameter("BaslamaZamani", baslamaZamani) :
                new ObjectParameter("BaslamaZamani", typeof(System.DateTime));
    
            var bitmeZamaniParameter = bitmeZamani.HasValue ?
                new ObjectParameter("BitmeZamani", bitmeZamani) :
                new ObjectParameter("BitmeZamani", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Gecmis_Izleme_Result>("SP_Gecmis_Izleme", terminalIdParameter, baslamaZamaniParameter, bitmeZamaniParameter);
        }
    
        public virtual ObjectResult<SP_GetAnimatedDataByTerminalId_Result> SP_GetAnimatedDataByTerminalId(Nullable<int> terminalId, Nullable<int> archiveID)
        {
            var terminalIdParameter = terminalId.HasValue ?
                new ObjectParameter("TerminalId", terminalId) :
                new ObjectParameter("TerminalId", typeof(int));
    
            var archiveIDParameter = archiveID.HasValue ?
                new ObjectParameter("archiveID", archiveID) :
                new ObjectParameter("archiveID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAnimatedDataByTerminalId_Result>("SP_GetAnimatedDataByTerminalId", terminalIdParameter, archiveIDParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_IhlalListesiByCompanyId_Result> SP_IhlalListesiByCompanyId(Nullable<int> companyId, Nullable<System.DateTime> dtBaslama, Nullable<System.DateTime> dtBitme)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var dtBaslamaParameter = dtBaslama.HasValue ?
                new ObjectParameter("DtBaslama", dtBaslama) :
                new ObjectParameter("DtBaslama", typeof(System.DateTime));
    
            var dtBitmeParameter = dtBitme.HasValue ?
                new ObjectParameter("DtBitme", dtBitme) :
                new ObjectParameter("DtBitme", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_IhlalListesiByCompanyId_Result>("SP_IhlalListesiByCompanyId", companyIdParameter, dtBaslamaParameter, dtBitmeParameter);
        }
    
        public virtual ObjectResult<SP_IhlalListesiByTerminalId_Result> SP_IhlalListesiByTerminalId(Nullable<int> terminalId, Nullable<System.DateTime> dateBaslama, Nullable<System.DateTime> dateBitme)
        {
            var terminalIdParameter = terminalId.HasValue ?
                new ObjectParameter("TerminalId", terminalId) :
                new ObjectParameter("TerminalId", typeof(int));
    
            var dateBaslamaParameter = dateBaslama.HasValue ?
                new ObjectParameter("DateBaslama", dateBaslama) :
                new ObjectParameter("DateBaslama", typeof(System.DateTime));
    
            var dateBitmeParameter = dateBitme.HasValue ?
                new ObjectParameter("DateBitme", dateBitme) :
                new ObjectParameter("DateBitme", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_IhlalListesiByTerminalId_Result>("SP_IhlalListesiByTerminalId", terminalIdParameter, dateBaslamaParameter, dateBitmeParameter);
        }
    
        public virtual ObjectResult<SP_KontakRaporu_Result> SP_KontakRaporu(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KontakRaporu_Result>("SP_KontakRaporu", companyIdParameter);
        }
    
        public virtual ObjectResult<SP_LoginBilgileri_Result> SP_LoginBilgileri(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LoginBilgileri_Result>("SP_LoginBilgileri", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<SP_PersonelTakipBilgileriByTerminalId_Result> SP_PersonelTakipBilgileriByTerminalId(Nullable<int> terminalId, Nullable<System.DateTime> dateBaslama, Nullable<System.DateTime> dateBitme)
        {
            var terminalIdParameter = terminalId.HasValue ?
                new ObjectParameter("TerminalId", terminalId) :
                new ObjectParameter("TerminalId", typeof(int));
    
            var dateBaslamaParameter = dateBaslama.HasValue ?
                new ObjectParameter("DateBaslama", dateBaslama) :
                new ObjectParameter("DateBaslama", typeof(System.DateTime));
    
            var dateBitmeParameter = dateBitme.HasValue ?
                new ObjectParameter("DateBitme", dateBitme) :
                new ObjectParameter("DateBitme", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PersonelTakipBilgileriByTerminalId_Result>("SP_PersonelTakipBilgileriByTerminalId", terminalIdParameter, dateBaslamaParameter, dateBitmeParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<SP_RolantiSuresiByCompanyId_Result> SP_RolantiSuresiByCompanyId(Nullable<int> companyId, Nullable<System.DateTime> bastarihi, Nullable<System.DateTime> bittarihi)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var bastarihiParameter = bastarihi.HasValue ?
                new ObjectParameter("bastarihi", bastarihi) :
                new ObjectParameter("bastarihi", typeof(System.DateTime));
    
            var bittarihiParameter = bittarihi.HasValue ?
                new ObjectParameter("bittarihi", bittarihi) :
                new ObjectParameter("bittarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RolantiSuresiByCompanyId_Result>("SP_RolantiSuresiByCompanyId", companyIdParameter, bastarihiParameter, bittarihiParameter);
        }
    
        public virtual ObjectResult<SP_RolantiSuresiByTerminalId_Result> SP_RolantiSuresiByTerminalId(Nullable<int> terminalID, Nullable<System.DateTime> baslamatarihi, Nullable<System.DateTime> bitmetarihi)
        {
            var terminalIDParameter = terminalID.HasValue ?
                new ObjectParameter("terminalID", terminalID) :
                new ObjectParameter("terminalID", typeof(int));
    
            var baslamatarihiParameter = baslamatarihi.HasValue ?
                new ObjectParameter("baslamatarihi", baslamatarihi) :
                new ObjectParameter("baslamatarihi", typeof(System.DateTime));
    
            var bitmetarihiParameter = bitmetarihi.HasValue ?
                new ObjectParameter("bitmetarihi", bitmetarihi) :
                new ObjectParameter("bitmetarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RolantiSuresiByTerminalId_Result>("SP_RolantiSuresiByTerminalId", terminalIDParameter, baslamatarihiParameter, bitmetarihiParameter);
        }
    
        public virtual ObjectResult<SP_Sample_Result> SP_Sample(Nullable<int> companyId, Nullable<System.DateTime> zaman)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var zamanParameter = zaman.HasValue ?
                new ObjectParameter("zaman", zaman) :
                new ObjectParameter("zaman", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Sample_Result>("SP_Sample", companyIdParameter, zamanParameter);
        }
    
        public virtual ObjectResult<SP_SeferPaketi_Result> SP_SeferPaketi(Nullable<int> companyId, Nullable<System.DateTime> dateBaslama, Nullable<System.DateTime> dateBitme, Nullable<int> role)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var dateBaslamaParameter = dateBaslama.HasValue ?
                new ObjectParameter("DateBaslama", dateBaslama) :
                new ObjectParameter("DateBaslama", typeof(System.DateTime));
    
            var dateBitmeParameter = dateBitme.HasValue ?
                new ObjectParameter("DateBitme", dateBitme) :
                new ObjectParameter("DateBitme", typeof(System.DateTime));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SeferPaketi_Result>("SP_SeferPaketi", companyIdParameter, dateBaslamaParameter, dateBitmeParameter, roleParameter);
        }
    
        public virtual ObjectResult<SP_TumAraclarByCompanyId_Result> SP_TumAraclarByCompanyId(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TumAraclarByCompanyId_Result>("SP_TumAraclarByCompanyId", companyIdParameter);
        }
    }
}
