//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_READ_IDENTITY
    {
        public int InfoID { get; set; }
        public int TerminalId { get; set; }
        public byte Yonu { get; set; }
        public int RfidCardId { get; set; }
        public System.DateTime ReadDate { get; set; }
        public int ArchiveId { get; set; }
    }
}
