//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DURAK_GIRIS_CIKIS
    {
        public int DurakGirisCikisId { get; set; }
        public int TerminalId { get; set; }
        public int DurakId { get; set; }
        public int DurakGirisId { get; set; }
        public int DurakCikisId { get; set; }
        public int GirisCikisSuresi { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
