//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DATA_MESSAGES
    {
        public int MessagesID { get; set; }
        public int TerminalId { get; set; }
        public string Komut { get; set; }
        public bool Durum { get; set; }
        public int IstekId { get; set; }
        public string MsgType { get; set; }
        public int TransCode { get; set; }
    }
}
