//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DURAK_IHLAL_MASTER
    {
        public int DurakIhlaId { get; set; }
        public int DurakSureId { get; set; }
        public int IhlalDurakId { get; set; }
    }
}
