//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CALISMA
    {
        public int Id { get; set; }
        public Nullable<int> TerminalId { get; set; }
        public Nullable<int> CalismaSuresi { get; set; }
        public Nullable<int> CalismaBaslamaId { get; set; }
        public Nullable<int> CalismaBitmeId { get; set; }
        public Nullable<System.DateTime> CalismaBaslamaTarih { get; set; }
        public Nullable<System.DateTime> CalismaBitmeTarih { get; set; }
    }
}
