//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ARCHIVE
    {
        public int ArchiveID { get; set; }
        public int TransCode { get; set; }
        public string UnitID { get; set; }
        public System.DateTime DateTimeLocal { get; set; }
        public System.DateTime DateTimeGps { get; set; }
        public decimal CoordinateX { get; set; }
        public decimal CoordinateY { get; set; }
        public decimal Speed { get; set; }
        public decimal Direction { get; set; }
        public decimal Distance { get; set; }
        public int Altitude { get; set; }
        public byte Ignition { get; set; }
        public byte NumberOfSatellite { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public string MsgType { get; set; }
        public string Status { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string District { get; set; }
        public string Quarter { get; set; }
        public string Street { get; set; }
        public Nullable<int> RolantiSuresi { get; set; }
        public string ipNumber { get; set; }
    }
}
