//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DURMA
    {
        public int Id { get; set; }
        public Nullable<int> TerminalId { get; set; }
        public Nullable<int> DurmaSuresi { get; set; }
        public Nullable<int> DurmaBaslamaId { get; set; }
        public Nullable<int> DurmaBitmeId { get; set; }
        public Nullable<System.DateTime> DurmaBaslamaTarih { get; set; }
        public Nullable<System.DateTime> DurmaBitmeTarih { get; set; }
    }
}
