//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ALARM
    {
        public int AlarmID { get; set; }
        public int ArchiveID { get; set; }
        public int TerminalID { get; set; }
        public int AlarmType { get; set; }
        public string AlarmMore { get; set; }
        public System.DateTime AlarmDate { get; set; }
        public System.DateTime LocalAlarmDate { get; set; }
        public int ContactType { get; set; }
        public string SpecCode { get; set; }
        public string ContactNumber { get; set; }
        public string TelemetryValue { get; set; }
    }
}
