//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVOICE
    {
        public int InvoiceID { get; set; }
        public int CompanyID { get; set; }
        public byte InvoiceMonthofDate { get; set; }
        public byte InvoicePeriod { get; set; }
        public decimal InvoiceAmount { get; set; }
        public string InvoiceName { get; set; }
    }
}
