//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KOMUT
    {
        public int KomutId { get; set; }
        public int TerminalId { get; set; }
        public string Komut { get; set; }
        public System.DateTime KomutTarihi { get; set; }
        public bool KomutDurum { get; set; }
        public Nullable<bool> sms { get; set; }
    }
}
