//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DURAKLAR_ARASI_SURE_TANIM
    {
        public int DurakSureId { get; set; }
        public int Durak1 { get; set; }
        public int Durak2 { get; set; }
        public int Sure { get; set; }
        public bool Yon { get; set; }
    }
}
