//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SEFER_PAKETI
    {
        public int SeferId { get; set; }
        public int TerminalId { get; set; }
        public string GpsVarmı { get; set; }
        public System.DateTime SeferBaslama { get; set; }
        public decimal BaslangicEnlem { get; set; }
        public decimal BaslangicBoylam { get; set; }
        public System.DateTime SeferBitme { get; set; }
        public decimal BitisEnlem { get; set; }
        public decimal BitisBoylam { get; set; }
        public decimal GidilenYol { get; set; }
        public decimal MaximumHiz { get; set; }
        public decimal SeferSuresi { get; set; }
        public decimal MaximumHizSuresi { get; set; }
        public decimal IlkHareketeKadarRolanti { get; set; }
        public decimal DurmaRolantiSuresi { get; set; }
        public decimal SonRolantiSuresi { get; set; }
        public string SurucuBilgisi { get; set; }
        public string BasCity { get; set; }
        public string BasCountry { get; set; }
        public string BasDistrict { get; set; }
        public string BasQuarter { get; set; }
        public string BasStreet { get; set; }
        public string BitCity { get; set; }
        public string BitCountry { get; set; }
        public string BitDistrict { get; set; }
        public string BitQuarter { get; set; }
        public string BitStreet { get; set; }
        public string BaslangicNoktasi { get; set; }
        public string BitisNoktasi { get; set; }
    }
}
