//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DURAK_DETAY
    {
        public int DurakDetayId { get; set; }
        public int TerminalId { get; set; }
        public int DurakId { get; set; }
        public bool GirisDurumDetay { get; set; }
        public decimal DurakDetayLat { get; set; }
        public decimal DurakDetayLng { get; set; }
        public System.DateTime DurakDetayTarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
