//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DURAK_TANIM
    {
        public int DurakId { get; set; }
        public string DurakAdi { get; set; }
        public decimal DurakOrgLat { get; set; }
        public decimal DurakOrgLng { get; set; }
        public decimal DurakMaxLat { get; set; }
        public decimal DurakMaxLng { get; set; }
        public decimal DurakMinLat { get; set; }
        public decimal DurakMinLng { get; set; }
        public int DurakNo { get; set; }
        public int CompanyId { get; set; }
    }
}
