//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DURAKLAR_ARASI_SURELER
    {
        public int SureId { get; set; }
        public int TerminalId { get; set; }
        public int GirisDurakId { get; set; }
        public int CikisDurakId { get; set; }
        public int GirisCikisSuresi { get; set; }
        public bool Yon { get; set; }
        public Nullable<System.DateTime> DurakGirisZaman { get; set; }
        public Nullable<System.DateTime> DurakCikisZaman { get; set; }
        public Nullable<int> IhlalDurumu { get; set; }
        public Nullable<int> IhlalSuresi { get; set; }
    }
}
