//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PROG_ANSWER
    {
        public int AnswerID { get; set; }
        public string MsgType { get; set; }
        public int TransCode { get; set; }
        public string UnitID { get; set; }
        public string CommandanData { get; set; }
    }
}
